---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

  - name: CREATE NODES
    bigip_node:
      provider:
        server: "{{ansible_host}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: 8443
        validate_certs: false
      host: "{{hostvars[item].ansible_host}}"
      state: "{{state}}"
      name: "{{hostvars[item].inventory_hostname}}"
    #loop: "{{ groups['tag_ansible_group_jboss'] }}"
    loop: "{{ groups['webservers'] }}"
